# Site settings
title: พระธรรมทูตไทยสายประเทศอินเดีย-เนปาล | Dhammaduta Bhikkhus Thai Mission in India-Nepal (DTIN)
email: admin@dhammadutabhikkhus.com
url: http://dhammadutabhikkhus.com
description: "พระธรรมทูตไทยสายประเทศอินเดีย-เนปาล | Dhammaduta Bhikkhus Thai Mission in India-Nepal (DTIN)"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#7D4712'
  links: '#E6BF73'
  text: '#fef0cb'

# Footer settings
footer: Dhammaduta Bhikkhus Thai <br class="mob-br">Mission in India-Nepal (DTIN)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Dhammaduta
  - title: facebook
    url: https://facebook.com/dhammadutabhikkhus/
  - title: youtube
    url: https://www.youtube.com/channel/UCUOgajYS0GmGkFhVx220vuw

# Build settings
markdown: kramdown
permalink: pretty
